name: Graduation_Project
description: ""
publish_to: "none"
version: 1.0.1+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # For using cupertino icons
  cupertino_icons: ^1.0.8
  win32: ^5.5.0

  # For integrating firebase
  firebase_core: ^3.1.0

  # For handling firebase authentication
  firebase_auth: ^5.1.0

  # For handling google sign in
  google_sign_in: ^6.2.1

  # For accessing cloud firestore database
  cloud_firestore: ^5.0.1

  # For showing network images
  cached_network_image: ^3.3.1

  # For picking images
  image_picker: ^1.1.2

  # For accessing Firebase Storage (for uploading files)
  firebase_storage: ^12.0.1

  # For showing Emojis
  emoji_picker_flutter: ^2.2.0

  # For accessing firebase messaging (Push Notification)
  firebase_messaging: ^15.0.1

  # Bearer Token for Push Notification
  googleapis_auth: ^1.6.0

  # For calling RestAPIs
  http: ^1.2.1

  # For creating notification channel
  flutter_notification_channel: ^3.1.0

  gallery_saver_updated: ^3.0.0




  google_generative_ai: ^0.4.3
    # flutter_localization: ^0.2.0
  #flutter_localizations:
  flutter_localizations:
    sdk: flutter

  flutter_chat_ui: ^1.6.13



  url_launcher: ^6.3.0

  text_field_custom: ^0.0.1
  flutter_firebase_chat_core: ^1.6.7
  flutter_chat_types: ^3.6.2
  get_storage: ^2.1.1
  get: ^4.6.6
  flutter_local_notifications: ^17.2.3
  ## flutter_native_timezone: ^2.0.0
  flutter_local_notifications_platform_interface: ^7.1.0
  flutter_timezone: ^1.0.8
  intl: ^0.19.0
  custom_flutter_button: ^0.0.1
  textfields: ^0.0.3
  google_fonts: ^6.2.1
  date_picker_timeline: ^1.2.6
  sqflite: ^2.3.3+1
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.10+1

  vm_service: ^14.2.1
  xml: ^6.5.0
  rxdart: ^0.27.2
  provider: ^6.1.2
  intl_utils: ^2.8.7
  xml2json: ^6.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  #   flutter_launcher_icons: "^0.10.0"

  # flutter_icons:
  #   android: "ic_launcher"
  #   ios: true
  #   image_path: "images/appicon.png"
  #   min_sdk_android: 21
  #   remove_alpha_ios: true

  # For recommended coding practices
  flutter_lints: ^4.0.0

flutter:
  # For enabling material design
  uses-material-design: true

  # App Assets
  assets:
    - images/



#SQLITE with moore for all platforms
moor: ^4.6.1+1
moor_flutter: ^4.1.0
ffi: ^2.1.2
# for sqlite on android
sqlite3_flutter_libs:
flutter_intl:
  enabled: true