// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJYw0XZ4gUIM7DT5rTHZtkexTjFur5_N4',
    appId: '1:406240150784:web:548747120bb4994b3f1fe5',
    messagingSenderId: '406240150784',
    projectId: 'hospital-6383a',
    authDomain: 'hospital-6383a.firebaseapp.com',
    storageBucket: 'hospital-6383a.appspot.com',
    measurementId: 'G-Z9NVW6JPEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa95cT-kyYWxqoNFCGZyHDCxxHWUBDaVY',
    appId: '1:406240150784:android:d3d0eafa7329d91a3f1fe5',
    messagingSenderId: '406240150784',
    projectId: 'hospital-6383a',
    storageBucket: 'hospital-6383a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHICj5g1GWde8uwTcrt6G3JyLY606h5nQ',
    appId: '1:406240150784:ios:ab671a90e129644d3f1fe5',
    messagingSenderId: '406240150784',
    projectId: 'hospital-6383a',
    storageBucket: 'hospital-6383a.appspot.com',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHICj5g1GWde8uwTcrt6G3JyLY606h5nQ',
    appId: '1:406240150784:ios:ab671a90e129644d3f1fe5',
    messagingSenderId: '406240150784',
    projectId: 'hospital-6383a',
    storageBucket: 'hospital-6383a.appspot.com',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR3I_xj-s4xgIJ_FN6beRN1a0POEInkiA',
    appId: '1:406240150784:web:de9b253d214aa21c3f1fe5',
    messagingSenderId: '406240150784',
    projectId: 'hospital-6383a',
    authDomain: 'hospital-6383a.firebaseapp.com',
    storageBucket: 'hospital-6383a.appspot.com',
    measurementId: 'G-KFK1MYK92W',
  );
}
